### ISSUE TITLE
Getting issue while installing requirements

### ISSUE THREAD

**Issue by Anitha19r** [ayoungprogrammer/nlquery#6]
Collecting lango==0.13.2 (from -r requirements.txt (line 1))
  Using cached Lango-0.13.2.tar.gz
Collecting pattern==2.6 (from -r requirements.txt (line 2))
  Using cached pattern-2.6.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7c/8ympcg21083b3pw4pxkyt52c0000gn/T/pip-build-zh8w8w3a/pattern/setup.py", line 40
        print n
              ^
    SyntaxError: Missing parentheses in call to 'print'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/7c/8ympcg21083b3pw4pxkyt52c0000gn/T/pip-build-zh8w8w3a/pattern/
--> python --version
Python 2.7.10

**Comment by ayoungprogrammer** [comment]
NLQuery uses python2.7 and I haven't had time to add backwards compatibility from python3. There are tools for upgrading NLQuery or you can switch to python2.7.
